---

- block:
  - name: Install dependencies on host
    apt:
      name: "{{ dependencies.lvm }}"
      state: present
      update_cache: no

  - name: Be sure to install lvm2 in target
    set_fact:
      install_packages: "{{ install_packages + dependencies.lvm }}"

  when: lvm|count > 0

- name: create volume groups
  lvg:
    state: present
    vg: "{{ vg }}"
    pvs: "{{ pvs }}"
  vars:
    pvs: "{{ lvm
            | selectattr('lvm', 'defined')
            | map(attribute='lvm')
            | selectattr('vg', 'eq', vg)
            | selectattr('pvs', 'defined')
            | map(attribute='pvs')
            | list
          }}"
  loop_control:
    loop_var: vg
  loop: "{{ lvm | selectattr('lvm', 'defined') | map(attribute='lvm') | selectattr('vg', 'defined') | map(attribute='vg') | list | unique }}"

- name: create LVM columes
  lvol:
    active: "{{ volume.lvm.active|default(omit) }}"
    force: "{{ volume.lvm.force|default(omit) }}"
    lv: "{{ volume.lvm.lv|default(omit) }}"
    opts: "{{ volume.lvm.opts|default(omit) }}"
    pvs: "{{ volume.lvm.pvs|default(omit) }}"
    size: "{{ volume.lvm.size|default(omit) }}"
    thinpool: "{{ volume.lvm.thinpool|default(omit) }}"
    vg: "{{ volume.lvm.vg|default(omit) }}"
  loop_control:
    loop_var: volume
    index_var: volume_num
  loop: "{{ lvm }}"

- name: add lv to devices
  set_fact:
    _tgt_devices: >
      {{ _tgt_devices|combine({"/dev/mapper/" + device.lvm.vg|replace("-", "--") + "-" + device.lvm.lv|replace("-", "--"): device|combine({'use_dev': True})}) }}
  loop_control:
    index_var: device_num
    loop_var: device
  when: "'lv' in device.lvm"
  loop: "{{ lvm }}"
